# Specify the language used in the project
language: node_js

# Specify the Node.js versions to be tested
node_js: 
  - 18

services:
  - docker

script:
  # Build image udagram-api-user
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user toanml/udagram-api-user:v1
  # Build image udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed toanml/udagram-api-feed:v1
  # Build image udagram-frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend toanml/udagram-frontend:v2
  # Build reverseproxy
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy toanml/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push toanml/udagram-api-user:v1
  - docker push toanml/udagram-api-feed:v1
  - docker push toanml/udagram-frontend:v2
  - docker push toanml/reverseproxy:v1
