version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: toanml/reverseproxy:lastest
  backend_user:
    build:
      context: ./udagram-api-user
    image: toanml/udagram-api-user:lastest
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: toanml/udagram-api-feed:lastest
  frontend:
    build:
      context: ./udagram-frontend
    image: toanml/udagram-frontend:lastest
