version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: toanml/udagram-reverseproxy:local
  backend_user:
    build:
      context: ./udagram-api-user
    image: toanml/udagram-api-user:local
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: toanml/udagram-api-feed:local
  frontend:
    build:
      context: ./udagram-frontend
    image: toanml/udagram-frontend:local
